### ISSUE TITLE
Could tests requiring real server connection auto-skip if no server is available?

### ISSUE THREAD

**Issue by yarikoptic** [pyxnat/pyxnat#105]
Tried to run the tests via
```
PYTHONPATH=$PWD /usr/bin/nosetests -v --exclude="test_(del_provenance|attr_mset|subject._delete)" pyxnat 
```

but 40 of them error out seems to be similarly with e.g.
```shell
======================================================================
ERROR: pyxnat.tests.attributes_test.test_fancy_resource_create
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/yoh/deb/gits/pkg-exppsy/pyxnat/pyxnat/tests/attributes_test.py", line 28, in test_fancy_resource_createxperiment.create(**field_data)
  File "/home/yoh/deb/gits/pkg-exppsy/pyxnat/pyxnat/core/resources.py", line 383, in create
    parent_element.create(**params)
  File "/home/yoh/deb/gits/pkg-exppsy/pyxnat/pyxnat/core/resources.py", line 383, in create
    parent_element.create(**params)
  File "/home/yoh/deb/gits/pkg-exppsy/pyxnat/pyxnat/core/resources.py", line 393, in create
    output = self._intf._exec(create_uri, 'PUT')
  File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /REST/projects/nosetests?xsiType=xnat:projectData (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe0facce190>: Failed to establish a new connection: [Errno 111] Connection refused',))
```

IMHO it would be best if tests were decorated to be skipped automatically if there is no XNAT server available on localhost:80 (unless such one is served by the test harness somehow).

Demanding unconditionally having XNAT server (via docker as now) to test complicates testing in scenarios where no docker could be installed/configured for that purpose (thus probably related to #76)

**Comment by xgrg** [comment]
Are you suggesting to skip tests based on the Docker instance only or all tests requiring an XNAT instance (e.g. Docker + [XNAT CENTRAL](https://central.xnat.org))? 

To date existing tests are divided into three main types:
- Tests with zero connectivity required (e.g. [jsonutil_test.py](https://github.com/pyxnat/pyxnat/blob/master/pyxnat/core/jsonutil.py))
- Tests against [CENTRAL](https://central.xnat.org) (e.g. [interfaces_test.py](https://github.com/pyxnat/pyxnat/blob/master/pyxnat/core/interfaces_test.py))
- Tests requiring higher privileges run against a Docker-based XNAT instance (e.g. [user_and_project_management_test.py](https://github.com/pyxnat/pyxnat/blob/master/pyxnat/core/user_and_project_management_test.py))

A complete list of these tests with their associated target may be found on this [spreadsheet](https://docs.google.com/spreadsheets/d/1aAj6zx65clKj7kNx_EsATF-_OdQU0CFQb6-yHnaRuuY/edit?usp=sharing).

Current distribution is still balanced between [CENTRAL](https://central.xnat.org) and the Docker instance. We are obviously still looking for the right strategy and it seems that none is absolutely free from flaws.

Moving all tests to [CENTRAL](https://central.xnat.org) (as suggested in https://github.com/pyxnat/pyxnat/issues/76) is indeed tempting but also proves to be suboptimal both due to the lacking privileges for some tests (and also instability issues e.g. it commonly happens that re-running a failed Travis test n times would eventually work). Therefore the need for a second instance with more liberal permissions. On the opposite, it is true that adding a hard dependency on a Docker instance is not the best option, as some contexts may not be compatible with it. The discussion seems to have been open for a long time. 

Anyway, this temptative https://github.com/pyxnat/pyxnat/pull/110 would move again some tests back to [CENTRAL](https://central.xnat.org) while a minimum amount would stick to the Dockerized instance (ref. [spreadsheet](https://docs.google.com/spreadsheets/d/1aAj6zx65clKj7kNx_EsATF-_OdQU0CFQb6-yHnaRuuY/edit?usp=sharing)). As suggested, some added decorator would allow to skip these few tests if connection to `localhost` cannot be established (in which case these features would actually remain untested). I am not sure https://github.com/pyxnat/pyxnat/pull/110  solves anything but at least it might contribute to the discussion. 

Could you please give it a quick look (or branch https://github.com/xgrg/pyxnat/tree/nosetests) and let hear some feedback?

Also, could you say more about which contexts are incompatible with having a subsidiary XNAT instance, aside from [CENTRAL](https://central.xnat.org)? Not necessarily Docker-based or public. Skipping tests is far from being perfect for obvious reasons.

Thank you @yarikoptic for raising (again) the subject. Hopefully this might help us moving towards a fair and efficient solution. Any help is welcome.

**Comment by yarikoptic** [comment]
> Are you suggesting to skip tests based on the Docker instance only or all tests requiring an XNAT instance (e.g. Docker + [XNAT CENTRAL](https://central.xnat.org))?

Quick one:
We typically run tests requiring network connectivity by default, but have a way to disable when (e.g. debian package buildtime testing) needed.  
Docker instances: ideally if it is possible to automate starting a docker instance as a session wide fixture -- we do that automagically (see e.g. https://github.com/ReproNim/reproman/blob/master/reproman/tests/fixtures.py#L23) .  If no docker available -- skip.  

My point was -- it should be sufficient to just run tests without requiring any manual labor to prepare my env for that.  If tests require some resource which is not available -- would be nice if they just skip.

Hope this helps

**Comment by xgrg** [comment]
Thanks for the quick feedback, it helps.
So in relation to your point, and if I understand well, current behavior (after merging https://github.com/pyxnat/pyxnat/pull/110) would be:

- The Docker-based XNAT instance is currently started, not by `nosetests`, but by Travis (https://github.com/pyxnat/pyxnat/blob/master/.travis.yml#L40) then populated by  [setup_xnat.py](https://github.com/pyxnat/pyxnat/blob/master/pyxnat/tests/setup_xnat.py). Then if a local XNAT connection cannot be created, corresponding tests will skip. If we want in the future to mimic the fixture in [reproman](https://github.com/ReproNim/reproman), running the instance should be handled by `nosetests`, not by Travis, I guess.

- Tests using [XNAT CENTRAL](https://central.xnat.org/) cannot be skipped at the moment. If we disable them, we end up with ~70% tests simply ignored. 

Just to know (not familiar with this), is it still a valid behavior even for package buildtime testing?

Many thanks again.

**Comment by yarikoptic** [comment]
> * If we want in the future to mimic the fixture in [reproman](https://github.com/ReproNim/reproman), running the instance should be handled by `nosetests`, not by Travis, I guess.

yeap ;)



> Thanks for the quick feedback, it helps.
> So in relation to your point, and if I understand well, current behavior (after merging #110) would be:
> 
> * The Docker-based XNAT instance is currently started, not by `nosetests`, but by Travis (https://github.com/pyxnat/pyxnat/blob/master/.travis.yml#L40) then populated by  [setup_xnat.py](https://github.com/pyxnat/pyxnat/blob/master/pyxnat/tests/setup_xnat.py). Then if a local XNAT connection cannot be created, corresponding tests will skip. If we want in the future to mimic the fixture in [reproman](https://github.com/ReproNim/reproman), running the instance should be handled by `nosetests`, not by Travis, I guess.

> * Tests using [XNAT CENTRAL](https://central.xnat.org/) cannot be skipped at the moment. If we disable them, we end up with ~70% tests simply ignored.

they shouldn't be disabled by default, but it should be possible to easily disable them (e.g. via env variable how we do it for all our toolkits, and python-mne does that too... smth like `PYXNAT_SKIP_NETWORK_TESTS` or alike, so if it is set to any value - a test requiring network access would be skipped.  
Another way would be a nose way to tag those tests with "network" tag and then use `nosetests ... -A "not network"` -- that is an approach taken by mpi4py IIRC

30% is still better than 0% to guarantee at least basic proper functionality and compatibility (syntax) with current version(s) of python during build time

> Just to know (not familiar with this), is it still a valid behavior even for package buildtime testing?

unless tests skip or could be easily disabled, nope.  Just think of package build being done on a computer which has no network connectivity (relates to https://wiki.debian.org/DesertIslandTest  and reliable package building).

**Comment by yarikoptic** [comment]
ah, a hint -- to quickly verify that all is kosher -- just run the tests with `http_proxy=http://127.0.0.1:9/ https_proxy=http://127.0.0.1:9/` environment variables.  Then anything pythonish trying to reach out to network should fail

**Comment by xgrg** [comment]
Great, thanks for the hints! So I tried something following this. Maybe not the most elegant but anyway...
Now every relevant test starts with:
```
if PYXNAT_SKIP_NETWORK_TESTS:
    raise SkipTest('No network. Skipping test.')
```

This was tested in simulated conditions (i.e. setting `http*_proxy`) and seems to behave as expected (coverage then falls from ~70% to ~47%). 

@jhuguetn has helped a lot on the whole thing. He is now away for a few weeks - so testing and code review will have to wait a bit. Unless you may want to give it a quick try already (https://github.com/pyxnat/pyxnat/pull/110).

Hope it will do the job. Thank you again @yarikoptic.

**Comment by yarikoptic** [comment]
FWIW, here is our `@skip_if_no_network` decorator in datalad which could easily adopt  and use to decorate your relevant tests   https://github.com/datalad/datalad/blob/master/datalad/tests/utils.py#L824

**Comment by xgrg** [comment]
Interesting, thanks @yarikoptic! 

Now, decorating the functions seems to change the execution order of the tests (not decorated: order of appearance - decorated: alphabetical order). Therefore `@skip_if_no_network` works beautifully when functions are independent (e.g. [array_test.py](https://github.com/xgrg/pyxnat/blob/nosetests/pyxnat/tests/array_test.py)) but seems to fail when order has some logic (e.g. first create experiment, set parameter, get parameter, clean experiment) (e.g. [attributes_test.py](https://github.com/xgrg/pyxnat/blob/nosetests/pyxnat/tests/attributes_test.py)). 

One would prefer unit tests to be totally independent, OK. For now I guess it is either we merge the tests (each cluster of dependent tests) into one big function, or we get the corresponding tests renamed `test_01_create`, `test_02_set`, etc (as in https://github.com/pyxnat/pyxnat/pull/110/commits/a4506187f930522b51d2cefb5c617e70ebd3fda0) ... Unless there is some other options?

**Comment by yarikoptic** [comment]
Ha, that is interesting! Never mentioned since we never relied on tests order since while developing often run just a single one before running all. There are also setup and tear down fixtures you could use to fix in the long run, or generator tests where I guess they should be executed in the order they are yielded. But all of those are more evolved that the renaming trick you are thinking about

**Comment by xgrg** [comment]
Sounds like a sound way to investigate, thanks a lot @yarikoptic.

@jhuguetn when you can would you please look at https://github.com/pyxnat/pyxnat/pull/110 so that we may move on with this issue? Thanks!

**Comment by xgrg** [comment]
PR was merged and will appear in next release. Thank you @yarikoptic and @jhuguetn.
