### ISSUE TITLE
pyxnat.Interface() displays IP and xnat password

### ISSUE THREAD

**Issue by samiraepp** [pyxnat/pyxnat#131]
Whenever I connect to xnat via 'pyxnat.Interface()', my username, ID and password is displayed which is of course an privacy issue when uploading my scripts to github. 
Has there yet been an attempt to make it non-verbose / not display the output?

**Comment by xgrg** [comment]
Did you try setting up a connection using a configuration file instead of plain credentials?
See `save_config` in http://pyxnat.github.io/pyxnat/starters_tutorial.html.

Once this configuration file created, you may pass it to the `Interface` constructor to connect to the XNAT instance without displaying any sensitive information in the script.

Also more details here: [First steps with pyxnat](http://xgrg.github.io/first-steps-with-pyxnat/).
Then you should be able to upload your code to GitHub such as in this [example](https://gist.github.com/xgrg/8ac0b489bc6266a40f9b40b24b238933).

@samiraepp does it help?

**Comment by samiraepp** [comment]
Creating an xnat_config.cfg file instead of an .xnatPass file, as provided in your example  [http://xgrg.github.io/first-steps-with-pyxnat/](url), worked wonders!
Thanks a lot!
