### ISSUE TITLE
Tests failing with authentication error

### ISSUE THREAD

**Issue by TheChymera** [pyxnat/pyxnat#76]
As part of the Zurich chapter of Brainhack global, we're looking to package your software for Gentoo Linux. The tests on version `1.0.1.0` fail with:

* `XPathEvalError: Undefined namespace prefix`
* what seems like an authentication error (code 403) - e.g. on the following address, which however works if accessed in the web browser or with `wget`

Full log here: http://bpaste.net/show/a67cc9ce3b7c

Any idea what can be done about this?

**Comment by johnflavin** [comment]
Thanks for posting the full log. The error response has a bunch of HTML, but buried in it is the more helpful message: `HTTP Status 403 - Your password has expired. Please try again after changing your password.`. Looking in the [test config file](https://github.com/pyxnat/pyxnat/blob/master/pyxnat/tests/central.cfg), it appears that the XNAT Central user that these tests run as is `nose`. 

I don't have admin credentials on Central to be able to fix this. @rherrick Can you take a look?

**Comment by johnflavin** [comment]
Several of the tests try to `GET /data/users` which fails with a `403` because they aren't authorized. `/data/users` is accessible to admins only, and we can't make this account an admin for obvious reasons. So I think those tests will have to be changed or removed.

Not sure about the `500` errors. Maybe they are transient and will go away next time?

**Comment by rherrick** [comment]
It would probably be better to start and populate XNAT in a Docker container for these tests. That would allow much better control over the contents and configuration of the target server. I'm not sure if there's a direct integration between nosetests and Docker but it seems pretty straightforward to work with docker-compose in python (which makes sense since docker-compose is written in python), so the XNAT docker-compose project would be a possibility...

**Comment by TheChymera** [comment]
I still get [the same errors](http://bpaste.net/show/2475a7b9cb88) on both `1.0.1.0` and the live version.

@rherrick

> It would probably be better to start and populate XNAT in a Docker container for these tests.

If by this you mean that you would rather execute the tests in Docker, I would very strongly advise against that. Docker does not provide dependency integration with the host system (or any sort of proper dependency management for that matter), so if you test in docker you can only vouch for usage in (that particular) docker. It is also particularly unwise to depend on docker in the first place, since it has a huge dependency stack and prerequires a large number of kernel options, whose availability you can't guarantee or expect.

**Comment by johnflavin** [comment]
I think what Rick is suggesting is not to run the tests themselves in docker, but to start an XNAT in docker using [nrgxnat/xnat-docker-compose](https://github.com/nrgxnat/xnat-docker-compose). That way the tests can be run against a fresh XNAT in a known good, controlled state, rather than using XNAT Central which is in an unknown, uncontrolled state.

**Comment by rherrick** [comment]
Yes on @johnflavin. I have unit tests for a Java library that requires PostgreSQL (uses JSON/JSONB data type, not available with H2 or HSQL). Rather than rely on having a full-blown PostgreSQL server configured and running, the build just launches the PostgreSQL Docker container and uses that. This does mean you're adding the dependency on Docker to the build environment, but the upside is that, once you have that, many other dependencies become trivial to handle, because they can be provided through services in Docker containers.

**Comment by TheChymera** [comment]
Sounds like instead of depending on PostgreSQL it now depends on PostgreSQL and Docker. Further, this puts PostgreSQL outside the reach of the package manager, so if you have specific requirements as to what exactly constitutes a "known, controlled" state of PostgreSQL (or XNAT in this case) you can no longer automatically resolve that. Docker isn't a package manager, but a way of doing manual and unstandardized dependency management with lots of overhead.

I'm thinking a remote solution might still be preferable:

* If XNAT Central is the sole public XNAT deployment, it stands to reason that if tests break with it, no significant guarantee can be made that those features will work during what constitutes normal usage. So the package actually *is* broken.
* If XNAT Central is not the sole public XNAT deployment, perhaps tests can be run against another one?

**Comment by xgrg** [comment]
Closing this. @TheChymera please reopen it if the problem still stands.
